### ISSUE TITLE
note app

### ISSUE THREAD

**Issue by Cluab** [ichala/web-phone#14]
### acknowledgments 💯 
- first of all, I would like to congratulate you on such an amazing project. I really enjoyed everything about it.
- amazing UX and UI.
- really enjoyed how you should sign in and the app displays your google profile picture and username in such a great manner.
- amazing work on the apps
### suggestions 💭 
- on the note app whenever I create a new note and search for it but misspell something and want to edit the misspelled text, nothing shows up. I must delete the entire search text so I can search again.

**Comment by ichala** [comment]
Hello @Cluab Thanks for mentioning this issue, it has been resolved in PR https://github.com/ichala/web-phone/pull/15

I appreciate it 🙏
